{% set version = '1.5-6' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-flexparamcurve
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/FlexParamCurve_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/FlexParamCurve/FlexParamCurve_{{ version }}.tar.gz
  sha256: ed0b18a8bd3336e20e268906d52a7909a07f480cf33069bbc905acc612490c5c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-nlme
  run:
    - r-base
    - r-nlme

test:
  commands:
    - $R -e "library('FlexParamCurve')"           # [not win]
    - "\"%R%\" -e \"library('FlexParamCurve')\""  # [win]

about:
  home: https://pennstate.academia.edu:443/SteveOswald
  license: GPL-2.0-only
  summary: Model selection tools and 'selfStart' functions to fit parametric curves in 'nls',
    'nlsList' and 'nlme' frameworks.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
